-- Run this entire script in the Supabase SQL Editor

CREATE TABLE IF NOT EXISTS generations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  primary_subject TEXT NOT NULL,
  specific_requirements TEXT,
  constraints TEXT,
  preferences TEXT,
  structured_prompt TEXT NOT NULL,
  ai_response TEXT NOT NULL,
  rating INTEGER DEFAULT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS actions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  generation_id BIGINT REFERENCES generations(id) ON DELETE CASCADE,
  action_type TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
